Does sunshine make people happy?
========================================================

Introduction
------------

It is well known that...


Methods
-------

```{r echo=FALSE} 
## Read data
data <- read.table("data.txt", header=T)
#data[10,1] <- 11   # correct error

# Fit linear model
model <- lm(happiness ~ sunshine, data=data)

```

We collected data on `r nrow(data)` individuals and fitted a linear model.



Results
-------

We found that...

```{r echo=FALSE, results='asis'}
# Print results
library(xtable, quietly=T)
kable(xtable(model), format="pandoc") # use format="pandoc" for converting to docx or pdf
```

```{r echo=FALSE}
# Plot
library(visreg, quietly=T)
visreg(model)
```

Discussion
----------

So these results confirm that sunshine is good for happiness (slope = `r coef(model)[2]`).





```{r echo=FALSE, message=FALSE}
# Convert output to pdf and docx format
#system("pandoc -o myproject.pdf myproject.md")
#system("pandoc -o myproject.docx myproject.md")

#pandoc("myproject.md", format="latex")
#pandoc("myproject.md", format="docx")
```
