---
title: "Does sunshine make people happy?"
author: "F. Rodriguez-Sanchez"
date: "Tuesday, November 25, 2014"
output: html_document

bibliography: references.bib
---

```{r citations_setup, include=FALSE}

library(knitcitations)
cite_options(citation_format = "pandoc")

```


Introduction
------------

It is well known that individual well-being can be influenced by climatic conditions `r citep("10.1016/j.ecolecon.2004.06.015")`. However, ...


Methods
-------

```{r echo=FALSE} 
## Read data
data <- read.table("data.txt", header=T)
#data[10,1] <- 11   # correct error

# Fit linear model
model <- lm(happiness ~ sunshine, data=data)

```

We collected data on `r nrow(data)` individuals and fitted a linear model.

```{r embed_data, results='asis',echo=FALSE, message=FALSE}

library(rmdTemplates)

embed_data_html('data')    # write name of your dataset here

```


```{r embed_Rmd, comment = NA, results = 'asis', echo = FALSE}

library(rmdTemplates)

embed_rmd_html("myproject_embed.Rmd")   # write name of the Rmd file here

```



Results
-------

We found that...

```{r echo=FALSE, results='asis'}
# Print results
library(xtable, quietly=T)
library(knitr)
kable(xtable(model)) 
```

```{r echo=FALSE}
# Plot
library(visreg, quietly=T)
visreg(model)
```

Discussion
----------

These results confirm that sunshine is good for happiness (slope = `r coef(model)[2]`).


Acknowledgements
----------------

Y. Xie, J. MacFarlane, Rstudio...


References
----------

```{r generate_references, cache=FALSE, include=FALSE, results='hide'}
write.bibtex(file="references.bib")
```



